site_name: Spring boot API Documentation
site_description: Spring boot API Documentation
site_author: Mi empresa

# Configuración de directorios
docs_dir: 'content'  # Los archivos markdown están en el directorio content
site_dir: 'site'  # La salida generada irá aquí

# Tema y configuración
theme:
  name: material
  palette:
    # Cambio de color principal a gris oscuro
    primary:
      - media: "(prefers-color-scheme)"
        scheme: default
        primary: grey
        accent: indigo
        toggle:
          icon: material/brightness-auto
          name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        scheme: slate
        primary: grey
        accent: indigo
        toggle:
          icon: material/brightness-4
          name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - toc.integrate
    - search.suggest
    - search.highlight
  language: es
  logo: assets/logo.png  # Ruta al logo
  favicon: assets/logo.png  # También usar el logo como favicon

# Extensiones de Markdown
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - footnotes
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - toc:
      permalink: true
      toc_depth: 3

# Navegación
nav:
  - Inicio: index.md
  - Instalación y Configuración: instalacion-configuracion.md
  - Endpoints:
      - General: endpoints.md
  - Modelo de Datos: modelos-datos.md
  - Documentación Funcional: documentacion-funcional.md
  - Ejemplos de Uso: ejemplos-uso.md


# Hojas de estilo adicionales
extra_css:
  - css/extra.css

# Otras configuraciones
plugins:
  - search
  - minify:
      minify_html: true

# Configuración de desarrollo
dev_addr: 0.0.0.0:9005

# Personalización del copyright
copyright: Copyright &copy; 2023 - 2025 Mi empresa
